# Generated by Django 5.1.3 on 2024-12-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_remove_profile_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verification_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_key_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
