# Generated by Django 5.1.3 on 2024-11-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_rename_userdetails_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
