# Generated by Django 5.0.7 on 2024-09-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_quantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_weight',
            new_name='weight',
        ),
        migrations.RemoveField(
            model_name='list',
            name='list_name',
        ),
        migrations.AddField(
            model_name='list',
            name='name',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
