# Generated by Django 5.1.3 on 2024-12-16 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_list_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='item',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='list',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='list',
            name='modified_by',
        ),
    ]
