# Generated by Django 5.1.3 on 2024-12-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0008_remove_item_is_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
